### ISSUE TITLE
Click link to dataset - filtered listing page shows up - but the the filter is not applied/reflected in the filters list (left)

### ISSUE THREAD

**Issue by aparnasr1** [CivicDataLab/IDS-DRR-Frontend#74]
- [x]  @ArcD7 to fix the filtering in elastic search
- [x]  Make the change on frontend to pick appropriate filter text

**Comment by ArcD7** [comment]
Category name should be same as indicator name in the facets category filter - @ruthvik129

**Comment by ruthvik129** [comment]
Made the changes and deployed on [dev](https://drr-dev.open-contracting.in/en) @aparnasr1 , Pl check
